#!/bin/sh
qemu-system-x86_64 -drive file=output/images/hd0,if=none,id=sata0,format=raw -device ich9-ahci,id=ahci -device ide-drive,drive=sata0,bus=ahci.0 -m 256M -monitor stdio -s -smp 8 -vnc 127.0.0.1:1 $*
